apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: cake-delight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: cake_delight_2-notification-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5003
          env:
            - name: PORT
              value: "5003"

            - name: MONGODB_URI
              value: "mongodb://notification-mongodb:27017/cake_delight_notifications"

            - name: RABBITMQ_URL
              value: "amqp://rabbitmq:5672"

            - name: EVENT_EXCHANGE
              value: "cake_delight_events"

            - name: NOTIFICATION_QUEUE
              value: "notification_service_queue"

            - name: NODE_ENV
              value: "production"
