apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-service
  namespace: cake-delight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rating-service
  template:
    metadata:
      labels:
        app: rating-service
    spec:
      containers:
        - name: rating-service
          image: cake_delight_2-rating-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5004
          env:
            - name: PORT
              value: "5004"

            - name: MONGODB_URI
              value: "mongodb://rating-mongodb:27017/rating_db"

            - name: NODE_ENV
              value: "production"
