apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: cake-delight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: cake_delight_2-api-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"

            - name: CATALOG_SERVICE_URL
              value: "http://catalog-service:5001/api/catalog"

            - name: ORDER_SERVICE_URL
              value: "http://order-service:5002/api/orders"

            - name: NOTIFICATION_SERVICE_URL
              value: "http://notification-service:5003/api/notifications"

            - name: RATING_SERVICE_URL
              value: "http://rating-service:5004/api/ratings"

            - name: NODE_ENV
              value: "production"
